CREATE TABLE UMSDB.AUDITS (
    AUDIT_ID int AUTO_INCREMENT PRIMARY KEY,
    AUTHOR varchar(50) NOT NULL,
	ACTION varchar(10) NOT NULL,
	TIMESTAMP datetime NOT NULL,
	ENTITY_TYPE varchar(10) NOT NULL,
    ENTITY text NOT NULL
);
