CREATE TABLE UMSDB.AUDITS (
    AUDIT_ID int AUTO_INCREMENT PRIMARY KEY,
    AUTHOR varchar(50) NOT NULL,
	ACTION varchar(10) NOT NULL,
	TIMESTAMP DATETIME NOT NULL,
    ENTITY varchar(5000) NOT NULL
);